catalogMode: strict
cleanupUnusedCatalogs: true
confirmModulesPurge: false
disallowWorkspaceCycles: true
saveWorkspaceProtocol: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - examples/*
  - tests/fixtures/*

catalogs:
  build:
    '@dvcol/eslint-config': 1.8.6
    '@prettier/plugin-xml': 3.4.2
    eslint: 10.8.0
    eslint-plugin-format: 2.0.1
    jiti: 2.7.0
    prettier: 3.9.6
    publint: 0.3.22
    tsdown: 0.22.14
    turbo: 2.10.8
  devtools:
    vite: 8.2.0
  testing:
    '@vitest/browser-playwright': 4.1.10
    '@vitest/coverage-v8': 4.1.10
    jsdom: 30.0.1
    playwright: 1.62.1
    vitest: 4.1.10
  types:
    '@types/node': 26.1.2
    typescript: 5.9.3
onlyBuiltDependencies:
  - esbuild
