export const cdpCapabilityLevels = ['observe', 'inspect', 'interact', 'debug', 'unsafe'] as const;

export type CdpCapabilityLevel = typeof cdpCapabilityLevels[number];

export const supportedChromeDebuggerDomains = [
  'Accessibility',
  'Audits',
  'CacheStorage',
  'Console',
  'CSS',
  'Database',
  'Debugger',
  'DOM',
  'DOMDebugger',
  'DOMSnapshot',
  'Emulation',
  'Fetch',
  'IO',
  'Input',
  'Inspector',
  'Log',
  'Network',
  'Overlay',
  'Page',
  'Performance',
  'Profiler',
  'Runtime',
  'Storage',
  'Target',
  'Tracing',
  'WebAudio',
  'WebAuthn',
] as const;

export type SupportedChromeDebuggerDomain = typeof supportedChromeDebuggerDomains[number];

export const kernelOwnedDomains = ['Target'] as const satisfies readonly SupportedChromeDebuggerDomain[];

type ClientFacingChromeDebuggerDomain = Exclude<SupportedChromeDebuggerDomain, typeof kernelOwnedDomains[number]>;

/** Broad defaults keep the reviewed policy legible; overrides capture methods whose direct purpose differs from their domain. */
export const commandLevelByDomain = {
  Accessibility: 'inspect',
  Audits: 'inspect',
  CacheStorage: 'inspect',
  Console: 'inspect',
  CSS: 'inspect',
  Database: 'inspect',
  Debugger: 'debug',
  DOM: 'inspect',
  DOMDebugger: 'debug',
  DOMSnapshot: 'inspect',
  Emulation: 'interact',
  Fetch: 'debug',
  IO: 'inspect',
  Input: 'interact',
  Inspector: 'observe',
  Log: 'inspect',
  Network: 'inspect',
  Overlay: 'interact',
  Page: 'interact',
  Performance: 'inspect',
  Profiler: 'debug',
  Runtime: 'inspect',
  Storage: 'inspect',
  Tracing: 'debug',
  WebAudio: 'inspect',
  WebAuthn: 'debug',
} as const satisfies Readonly<Record<ClientFacingChromeDebuggerDomain, CdpCapabilityLevel>>;

export const eventLevelByDomain = {
  Accessibility: 'inspect',
  Audits: 'inspect',
  CacheStorage: 'inspect',
  Console: 'inspect',
  CSS: 'inspect',
  Database: 'inspect',
  Debugger: 'debug',
  DOM: 'inspect',
  DOMDebugger: 'debug',
  DOMSnapshot: 'inspect',
  Emulation: 'interact',
  Fetch: 'debug',
  IO: 'inspect',
  Input: 'interact',
  Inspector: 'observe',
  Log: 'inspect',
  Network: 'inspect',
  Overlay: 'interact',
  Page: 'inspect',
  Performance: 'inspect',
  Profiler: 'debug',
  Runtime: 'inspect',
  Storage: 'inspect',
  Tracing: 'debug',
  WebAudio: 'inspect',
  WebAuthn: 'debug',
} as const satisfies Readonly<Record<ClientFacingChromeDebuggerDomain, CdpCapabilityLevel>>;

export const commandLevelOverrides = {
  'CacheStorage.deleteCache': 'interact',
  'CacheStorage.deleteEntry': 'interact',
  'Console.clearMessages': 'interact',
  'CSS.addRule': 'interact',
  'CSS.createStyleSheet': 'interact',
  'CSS.forcePseudoState': 'interact',
  'CSS.forceStartingStyle': 'interact',
  'CSS.setContainerQueryConditionText': 'interact',
  'CSS.setContainerQueryText': 'interact',
  'CSS.setEffectivePropertyValueForNode': 'interact',
  'CSS.setKeyframeKey': 'interact',
  'CSS.setLocalFontsEnabled': 'interact',
  'CSS.setMediaText': 'interact',
  'CSS.setNavigationText': 'interact',
  'CSS.setPropertyRulePropertyName': 'interact',
  'CSS.setRuleSelector': 'interact',
  'CSS.setScopeText': 'interact',
  'CSS.setStyleSheetText': 'interact',
  'CSS.setStyleTexts': 'interact',
  'CSS.setSupportsText': 'interact',
  'CSS.startRuleUsageTracking': 'debug',
  'CSS.stopRuleUsageTracking': 'debug',
  'CSS.trackComputedStyleUpdates': 'debug',
  'CSS.trackComputedStyleUpdatesForNode': 'debug',
  'DOM.copyTo': 'interact',
  'DOM.focus': 'interact',
  'DOM.forceShowPopover': 'interact',
  'DOM.hideHighlight': 'interact',
  'DOM.highlightNode': 'interact',
  'DOM.highlightRect': 'interact',
  'DOM.markUndoableState': 'interact',
  'DOM.moveTo': 'interact',
  'DOM.redo': 'interact',
  'DOM.removeAttribute': 'interact',
  'DOM.removeNode': 'interact',
  'DOM.scrollIntoViewIfNeeded': 'interact',
  'DOM.setAttributeValue': 'interact',
  'DOM.setAttributesAsText': 'interact',
  'DOM.setFileInputFiles': 'interact',
  'DOM.setInspectedNode': 'interact',
  'DOM.setNodeName': 'interact',
  'DOM.setNodeStackTracesEnabled': 'debug',
  'DOM.setNodeValue': 'interact',
  'DOM.setOuterHTML': 'interact',
  'DOM.undo': 'interact',
  'DOMDebugger.getEventListeners': 'inspect',
  'Emulation.canEmulate': 'observe',
  'Emulation.getOverriddenSensorInformation': 'inspect',
  'Emulation.getScreenInfos': 'inspect',
  'Debugger.disassembleWasmModule': 'inspect',
  'Debugger.getPossibleBreakpoints': 'inspect',
  'Debugger.getScriptSource': 'inspect',
  'Debugger.getStackTrace': 'inspect',
  'Debugger.getWasmBytecode': 'inspect',
  'Debugger.nextWasmDisassemblyChunk': 'inspect',
  'Debugger.searchInContent': 'inspect',
  'Fetch.getResponseBody': 'inspect',
  'Log.clear': 'interact',
  'Log.startViolationsReport': 'debug',
  'Log.stopViolationsReport': 'debug',
  'Network.clearAcceptedEncodingsOverride': 'interact',
  'Network.clearBrowserCache': 'interact',
  'Network.clearBrowserCookies': 'interact',
  'Network.configureDurableMessages': 'debug',
  'Network.deleteCookies': 'interact',
  'Network.deleteDeviceBoundSession': 'interact',
  'Network.emulateNetworkConditions': 'interact',
  'Network.emulateNetworkConditionsByRule': 'interact',
  'Network.enableDeviceBoundSessions': 'debug',
  'Network.enableReportingApi': 'debug',
  'Network.fetchSchemefulSite': 'interact',
  'Network.loadNetworkResource': 'interact',
  'Network.overrideNetworkState': 'interact',
  'Network.replayXHR': 'interact',
  'Network.setAcceptedEncodings': 'interact',
  'Network.setAttachDebugStack': 'debug',
  'Network.setBlockedURLs': 'interact',
  'Network.setBypassServiceWorker': 'interact',
  'Network.setCacheDisabled': 'interact',
  'Network.setCookie': 'interact',
  'Network.setCookieControls': 'interact',
  'Network.setCookies': 'interact',
  'Network.setExtraHTTPHeaders': 'interact',
  'Network.setUserAgentOverride': 'interact',
  'Network.streamResourceContent': 'debug',
  'Network.canClearBrowserCache': 'observe',
  'Network.canClearBrowserCookies': 'observe',
  'Network.canEmulateNetworkConditions': 'observe',
  'Overlay.getGridHighlightObjectsForTest': 'inspect',
  'Overlay.getHighlightObjectForTest': 'inspect',
  'Overlay.getSourceOrderHighlightObjectForTest': 'inspect',
  'Page.addCompilationCache': 'debug',
  'Page.addScriptToEvaluateOnLoad': 'debug',
  'Page.addScriptToEvaluateOnNewDocument': 'debug',
  'Page.captureScreenshot': 'inspect',
  'Page.captureSnapshot': 'inspect',
  'Page.clearCompilationCache': 'debug',
  'Page.crash': 'unsafe',
  'Page.createIsolatedWorld': 'debug',
  'Page.getAdScriptAncestry': 'inspect',
  'Page.getAnnotatedPageContent': 'inspect',
  'Page.getAppId': 'inspect',
  'Page.getAppManifest': 'inspect',
  'Page.getFrameTree': 'inspect',
  'Page.getInstallabilityErrors': 'inspect',
  'Page.getLayoutMetrics': 'inspect',
  'Page.getManifestIcons': 'inspect',
  'Page.getNavigationHistory': 'inspect',
  'Page.getOriginTrials': 'inspect',
  'Page.getPermissionsPolicyState': 'inspect',
  'Page.getResourceContent': 'inspect',
  'Page.getResourceTree': 'inspect',
  'Page.printToPDF': 'inspect',
  'Page.produceCompilationCache': 'debug',
  'Page.removeScriptToEvaluateOnLoad': 'debug',
  'Page.removeScriptToEvaluateOnNewDocument': 'debug',
  'Page.screencastFrameAck': 'debug',
  'Page.searchInResource': 'inspect',
  'Page.setBypassCSP': 'debug',
  'Page.setDownloadBehavior': 'unsafe',
  'Page.setInterceptFileChooserDialog': 'debug',
  'Page.startScreencast': 'debug',
  'Page.stopScreencast': 'debug',
  'Page.waitForDebugger': 'debug',
  'Performance.setTimeDomain': 'debug',
  'Profiler.getBestEffortCoverage': 'inspect',
  'Runtime.addBinding': 'debug',
  'Runtime.callFunctionOn': 'debug',
  'Runtime.compileScript': 'debug',
  'Runtime.discardConsoleEntries': 'debug',
  'Runtime.evaluate': 'debug',
  'Runtime.removeBinding': 'debug',
  'Runtime.runIfWaitingForDebugger': 'debug',
  'Runtime.runScript': 'debug',
  'Runtime.setAsyncCallStackDepth': 'debug',
  'Runtime.setCustomObjectFormatterEnabled': 'debug',
  'Runtime.setMaxCallStackSizeToCapture': 'debug',
  'Runtime.terminateExecution': 'debug',
  'Storage.clearCookies': 'interact',
  'Storage.clearDataForOrigin': 'interact',
  'Storage.clearDataForStorageKey': 'interact',
  'Storage.clearSharedStorageEntries': 'interact',
  'Storage.clearTrustTokens': 'interact',
  'Storage.deleteSharedStorageEntry': 'interact',
  'Storage.deleteStorageBucket': 'interact',
  'Storage.overrideQuotaForOrigin': 'interact',
  'Storage.resetSharedStorageBudget': 'interact',
  'Storage.runBounceTrackingMitigations': 'interact',
  'Storage.setCookies': 'interact',
  'Storage.setSharedStorageEntry': 'interact',
  'Storage.setSharedStorageTracking': 'debug',
  'Storage.setStorageBucketTracking': 'debug',
  'Storage.trackCacheStorageForOrigin': 'debug',
  'Storage.trackCacheStorageForStorageKey': 'debug',
  'Storage.trackIndexedDBForOrigin': 'debug',
  'Storage.trackIndexedDBForStorageKey': 'debug',
  'Storage.untrackCacheStorageForOrigin': 'debug',
  'Storage.untrackCacheStorageForStorageKey': 'debug',
  'Storage.untrackIndexedDBForOrigin': 'debug',
  'Storage.untrackIndexedDBForStorageKey': 'debug',
  'Tracing.getCategories': 'inspect',
  'Tracing.getTrackEventDescriptor': 'inspect',
  'WebAuthn.getCredential': 'inspect',
  'WebAuthn.getCredentials': 'inspect',
} as const satisfies Readonly<Record<string, CdpCapabilityLevel>>;

export const eventLevelOverrides = {
  'Emulation.screenOrientationLockChanged': 'observe',
  'Emulation.virtualTimeBudgetExpired': 'observe',
  'Page.screencastFrame': 'debug',
  'Page.screencastVisibilityChanged': 'debug',
} as const satisfies Readonly<Record<string, CdpCapabilityLevel>>;
